# rubocop:disable Metrics/BlockLength

FactoryGirl.define do
  factory :photo do
    id ''
    user_id ''
    name ''
    description ''
    camera ''
    lens ''
    focal_strength ''
    iso ''
    shutter_speed ''
    aperature ''
    times_viewed ''
    rating ''
    rating ''
    status ''
    created_at ''
    category ''
    category ''
    location ''
    longitude ''
    taken_at ''
    hi_res_uploaded ''
    for_sale ''
    width ''
    height ''
    votes_count ''
    favorites_count ''
    comments_count ''
    nsfw ''
    sales_count ''
    for_sale_date ''
    highest_rating ''
    highest_rating_date ''
    license_type ''
    converted ''
    collections_count ''
    crop_version ''
    privacy ''
    profile ''
    image_url ''
    images ''
    url ''
    positive_votes_count ''
    converted_bits ''
    watermark ''
    image_format ''
    user ''
    licensing_requested ''
    licensing_suggested ''
    is_free_photo ''
  end
end
