# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019b7e339c8f29619157e82c222dd948b972ab170c3ba4eb0b4719ec26f1839092da080e036bdf2b21eb0c002ee4e4f590c92e52c479aeac50867c0f0709a7f6

test:
  secret_key_base: 1e6ac2d1bd85bc1306cdab7bbb28cc5c2a78eb2fa53cd11a79ed6b42dce9a3404e97fbe1c2d35e365bef7507e9f9ec974e87709edf3ff7da1418042a7366674e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
